
esphome:
  name: combi_boiler
  friendly_name: combi_boiler
  platform: ESP32
  board: esp32dev

# Enable logging
logger:
   level: debug 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Boiler Fallback Hotspot"
    password: "Blablabla3!"

# Enable Home Assistant API
api:

# Enable Over-the-Air updates
ota:
  - platform: esphome
  
web_server:
  local: true
  port: 80

external_components:
  - source:
      type: local
      path: components

captive_portal:

font:
  - file: 'fonts/Silkscreen-Regular.ttf'
    id: font_slkscr_8
    size: 8
    glyphs: "!%()+,-/_.:°0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz"
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_48
    size: 48
  - file: 'fonts/BebasNeue-Regular.ttf'
    id: font_bebas_56
    size: 56
  - file: 'fonts/arial.ttf'
    id: font_arial_12
    size: 12

# Add multiple SPI configurations
spi:
  - id: "temp"
    miso_pin: 37
    mosi_pin: 27
    clk_pin: 13
  - id: "displ"
    clk_pin: 18
    mosi_pin: 19

# Add time component for display
time:
  - platform: homeassistant
    id: esptime

switch:
  - platform: gpio
    pin: GPIO4
    name: "Backlight"
    id: backlight
    restore_mode : ALWAYS_ON

  - platform: template
    name: "Boiler1 Enable"
    id: boiler1_switch
    restore_mode : RESTORE_DEFAULT_ON 
    turn_on_action:
      - logger.log: "turn_on_action"
      - lambda: |-
          id(my_boiler).set_boiler1_enabled(1);
          id(boiler1_switch).publish_state(true);
    turn_off_action:
      - logger.log: "turn_off_action"
      - lambda: |-
          id(my_boiler).set_boiler1_enabled(0);
          id(boiler1_switch).publish_state(false);
          
  - platform: template
    name: "Boiler2 Enable"
    id: boiler2_switch
    restore_mode : RESTORE_DEFAULT_ON 
    turn_on_action:
      - lambda: |-
          id(my_boiler).set_boiler2_enabled(1);
          id(boiler2_switch).publish_state(true);
    turn_off_action:
      - lambda: |-
          id(my_boiler).set_boiler2_enabled(0);
          id(boiler2_switch).publish_state(false);

  - platform: restart
    name: "Restart"
    
  - platform: safe_mode
    name: "Restart (Safe Mode)"
    
    
    

color:
  - id: color_red
    red: 1
    green: 0
    blue: 0
  - id: color_green
    red: 0
    green: 1
    blue: 0
  - id: color_blue
    red: 0
    green: 0
    blue: 1
  - id: color_orange
    red: 1
    green: 0.6
    blue: 0
  - id: color_teal_blue
    red: 0
    green: 0.5
    blue: 0.45

# Add display configuration
display:
  - platform: ili9xxx
    model: st7789v
    #TTGO TDisplay 135x240
    dimensions:
      height: 240
      width: 135
      offset_height: 40
      offset_width: 52
    invert_colors: true
    dc_pin: GPIO16
    reset_pin: GPIO23
    spi_id: displ
    cs_pin: GPIO5
    rotation: 90°
    #brightness: 0.5
    update_interval: 1s
    lambda: |-
      it.strftime(4, 4, id(font_slkscr_8), id(color_teal_blue), "%Y-%m-%d %H:%M", id(esptime).now());
      it.printf(16, 18, id(font_bebas_48), id(color_green), "%.1f °C %.0f %%", id(temperature1).state, id(boiler1_power).state);
      it.printf(16, 72, id(font_bebas_48), id(color_red), "%.1f °C %.0f %%", id(temperature2).state, id(boiler2_power).state);

# Rest of the configuration remains the same...


# Add the template numbers for both boilers
number:
  - platform: template
    name: "Boiler 1 forcepoint"
    id: boiler1_forcepoint
    restore_value: True
    min_value: -1
    max_value: 100
    step: 1
    initial_value: -1
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(my_boiler).set_boiler1_forcepoint(x);

  - platform: template
    name: "Boiler 2 forcepoint"
    id: boiler2_forcepoint
    restore_value: True
    min_value: -1
    max_value: 100
    step: 1
    initial_value: -1
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(my_boiler).set_boiler2_forcepoint(x);
            
  - platform: template
    name: "Boiler 1 max temperature"
    id: boiler1_max
    min_value: -1
    max_value: 100
    step: 1
    initial_value: 75
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(my_boiler).set_boiler1_setmax(x);

  - platform: template
    name: "Boiler 2 max temperature"
    id: boiler2_max
    min_value: -1
    max_value: 100
    step: 1
    initial_value: 40
    optimistic: true
    set_action:
      then:
        - lambda: |-
            id(my_boiler).set_boiler2_setmax(x);    

debug:
  update_interval: 5s

#text_sensor:
#  - platform: debug
#    device:
#      name: "Device Info"
#    reset_reason:
#      name: "Reset Reason"

sensor:
  - platform: debug
#    free:
#      name: "Heap Free"
#    block:
#      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
#    psram:
#      name: "Free PSRAM"         

  - platform: uptime
    type: seconds
    name: Uptime Sensor

  # MAX31865 Temperature Sensors
  - platform: max31865
    spi_id: temp
    name: "Temperature1"
    id: temperature1
    cs_pin: 33
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    rtd_wires: 3
    mains_filter: 50hz
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 0
    update_interval: 1s
    filters:
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1
      - calibrate_linear:
        - -0.7 -> 0
        - 98.9 -> 100
    
  - platform: max31865
    spi_id: temp
    name: "Temperature2"
    id: temperature2
    cs_pin: 32
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    rtd_wires: 3
    mains_filter: 50hz
    unit_of_measurement: "°C"
    icon: "mdi:water-percent"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 0
    update_interval: 1s
    filters:
      - median:
          window_size: 5
          send_every: 5
          send_first_at: 1
      - calibrate_linear:
        - 0.8 -> 0
        - 101.1 -> 100

  - platform: combi_boiler
    name: "Boiler 1 Power"
    id: boiler1_power
    combi_boiler_id: my_boiler
    sensor_number: 1
    temperature_id: temperature1
    unit_of_measurement: "%"
    icon: "mdi:power"
    accuracy_decimals: 1

  - platform: combi_boiler
    name: "Boiler 2 Power"
    id: boiler2_power
    combi_boiler_id: my_boiler
    sensor_number: 2
    temperature_id: temperature2
    unit_of_measurement: "%"
    icon: "mdi:power"
    accuracy_decimals: 1
      
binary_sensor:
  - platform: combi_boiler
    name: "Boiler 1 Full"
    sensor_number: 1
    
  - platform: combi_boiler
    name: "Boiler 2 Full"
    sensor_number: 2
    
text_sensor:
  - platform: combi_boiler
    name: "Boiler 1 Status"
    sensor_number: 1

  - platform: combi_boiler
    name: "Boiler 2 Status"
    sensor_number: 2

# Add the combi_boiler component
combi_boiler:
  id: my_boiler